### ISSUE TITLE
Security checklist

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#200]
Risk Management
---------------
* [ ] The service must have performed a Rapid Risk Assessment and have a Risk Record bug (**SVC-RRA**).
 
Infrastructure rules
--------------------
 
* [x] Use [Intermediate TLS](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) (**INFRA-TLS**)
* [x] Set HSTS to 31536000 (1 year) (**INFRA-HSTS**)
* [x] Set HPKP to 5184000 (60 days) (**INFRA-HPKP**)
  * `Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";`
    * Start with max-age set to 5 minutes (`max-age=300`) and increase progressively
    * The first two pins are for Digicert EV and DV roots, the last two are for Let's Encrypt X3 and X4 intermediates (LE is only used for backup)
  * [x] If the service is not hosted under `services.mozilla.com`, it must be manually added to [Firefox's preloaded pins](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#184).
* If service has an admin panels, it must:
  * [x] only be available behind Mozilla VPN (which provides MFA) (**INFRA-ADMINVPN**)
  * [x] require LDAP authentication (**INFRA-ADMINLDAP**)
  * [x] enforce a two-man rule on sensitive changes (**INFRA-2MANRULE**)
 
Coding rules
------------
 
The following rules apply to all web applications: api and websites.
 
* [x] Sign all release tags, and maybe commits (**APP-COMMITSIG**)
  * Developers should [configure git to sign all tags](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
  * The signature verification will eventually become a requirement to shipping a release to staging & prod: the tag being deployed in the pipeline must have a matching tag in git signed by a project owner. This control is designed to reduce the risk of a 3rd party GitHub integration from compromising our source code.
* [ ] Detailed logging in mozlog format (**APP-MOZLOG**)
  * Business logic must be logged with app specific codes (errno)
  * Access control failures must be logged at WARN level
* [x] Must have a CSP with (**APP-CSP**)
  * [ ] a report-uri pointing to the service's own `/__cspreport__` endpoint
  * [x] web APIs should set `default-src` to `none`, disallowing all content rendering
  * [x] if default-src is not `self`, frame-src should be `none` or only allow specific origins
  * [x] no use of unsafe-inline or unsafe-eval
* [ ] User data must be escaped for the right context prior to reflecting it (**APP-ESCAPE**)
* [ ] Web APIs must set a non-HTML content-type on all responses, including 300s, 400s and 500s
* [ ] All SQL queries must be parameterized, not concatenated (**APP-SQL**)
* [ ] Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation) (**APP-INPUTVAL**)
* [ ] Enforce Access Controls server-side (**APP-ACL**)
* [ ] Set the Secure flag on [Cookies](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies), and use sensible Expiration and HTTPOnly (**APP-SECCOOKIE**)
* Keep 3rd-party libraries up to date (**APP-DEPS**)
  * [ ]  Use [NSP](https://nodesecurity.io/) or [GreenKeeper](https://greenkeeper.io/ Greenkeeper) for NodeJS applications
  * [ ] Use pip --outdated or [requires.io](https://requires.io/) for Python applications
* [ ] If handling cryptographic keys, must have a mechanism to handle monthly key rotations (**APP-KEYROT**)
  * [ ] All keys must be rotated quarterly.
  * Keys used to sign sessions don't need a rotation mechanism if destroying all sessions is acceptable during.
 
### Additional websites requirements
 
The following coding rules only apply to websites, not web apis.
 
* [x] Never store passwords, use Firefox Accounts (**APP-IDP**)
* [x] Forbid Mixed content, always use HTTPS (**APP-MIXCONTENT**)
* [x] Must have CSRF tokens and manually excluded specific forms (**APP-CSRF**)
* [x] Should consider having checksums for 3rd-party content via SRI (**APP-SRI**).
  * Trusted 3rd parties, like Google Analytics, don't need SRI. Use your best judgment to decide if a 3rd party script is trustworthy (and assume it is not).
* Set the following security headers (**APP-HEADERS**)
  * [x] X-Content-Type-Options
  * [x] X-Frame-Options
  * [x] X-XSS-Protection
 
Data rules
----------
 
* When storing sensitive user data (like browsing history) on Mozilla servers:
  * [ ] Anonymize it (similar to Tiles) (**DATA-ANON**)
  * [ ] Encrypt it client-side (similar to Sync) (**DATA-CRYPT**)
  * [ ] If user data must be stored non-anonymized and in clear text, you must talk to the security and legal teams about it.
* If the service pushes data to Firefox, like when distributing blacklists or pushing updates, cryptographic signatures must be used. (**DATA-SIGN**)
  * [ ] Addons must use standard AMO signing (**APP-SIGNING**)
  * [ ] Code & Conf must use Content-Signature via [Autograph](https://github.com/mozilla-services/autograph) (**DATA-SIGNING**)

**Comment by marumari** [comment]
The reason why we changed it to two years as a recommendation was that there are many sites (Christmas shopping, taxes, etc.) that you sometimes visit more than a year apart.

**Comment by marumari** [comment]
Here was the conversation about moving it to two years, if it's helpful:

https://github.com/chromium/hstspreload.org/issues/62

**Comment by floatingatoll** [comment]
Thread context here: For HSTS durations,
https://github.com/mozilla/wikimo_content/pull/84 raises this to 2 years,
but https://wiki.mozilla.org/Security/FoxSec#Security_Checklist indicates 1
years, so the HSTS recommendation of 1 year here is correct and appropriate
since it's referencing the latter.

**Comment by jvehent** [comment]
Ok, this is a good discussion, but not here. This issue is about bringing TLS Observatory to compliance with the checklist, not updating the checklist itself.
Checklist discussion should be moved to https://github.com/mozilla-services/cloudsec/issues
